Silence a noisy __del__
Popped up sometimes, looking something like:

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7ff8f47827f0>>
Traceback (most recent call last):
  File "[...]tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

Which I'm guessing is TF_DeleteSession being None.

PiperOrigin-RevId: 227712751