contrib/lite: add missing include assert.h (spectrogram.cc) (#17573)
tensorflow/contrib/lite/build_ios_universal_lib.sh fails with:

    error: use of undeclared identifier 'assert'