[ROCm] Explicitly calling the nccl_manager_test in the ROCm CSB script
The ROCm CSB script relies on the `nccl_manager_test` test having the `rocm_multi_gpu` tag in order to invoke it. However adding the `rocm_multi_gpu` on that test seems to be adversely affecting the CUDA runs, and hence that tag ahs not been applied to the test in the upstream repo.
(for details, see the TODO in the file tensorflow/core/nccl/BUILD : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/nccl/BUILD#L55 )

Since this would have been the only test with the "rocm_mutli_gpu" tag, not having that tag results in the second bazel command (within the `linux/rocm/run_csb_tests.sh` script) failing with the following error

```
ERROR: No test targets were found, yet testing was requested
```

which then leads to the script exiting with an error status.

So until the "mutli_rocm_gpu" tag is re-applied to the test, we need to the change the ROCm CSB script to explicitly call this test (as opposed to specifying it via --test_tag_filters)