Fix syntax error in single_image_random_dot_stereograms caused by locale
This fix tries to address the issue raised in 21164 where
the single_image_random_dot_stereograms in different locale
(like de_DE) caused syntax error in python like:
```
File "<string>", line 28
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=2,5, mu=0,333299994, normalize=True, normalize_max=-100, normalize_min=100, border_level=0, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                      ^
SyntaxError: invalid syntax
```

The issue was that the float to string conversion in
python_op_gen_internal.cc triggered snprintf (in `FloatToBuffer`) which is local
dependent and generates something like `eye_separatiion=2,5` in DE locale.

This fix replaced the float to string conversion with locale-independent
```
      std::ostringstream s;
      s.imbue(std::locale::classic());
```

This fix fixes 21164.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>