Fix dense_shape check.
This rectifies the following error:

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is
not None:` instead of `if t:` to test if a tensor is defined, and use the
logical TensorFlow ops to test the value of a tensor.

when the conditional branch contains a tf.IndexedSlices object with
dense_shape=tf.constant(...).
Change: 117937593