update message to ask user to also install scipy
Following the word2vec tutorial instructions I tried "pip3 install sklearn matplotlib" but this didn't install the required "scipy". Adding that to the ImportError message.

>>> from sklearn.manifold import TSNE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/usr/local/lib/python3.5/site-packages/sklearn/base.py", line 9, in <module>
    from scipy import sparse
ImportError: No module named 'scipy'