EagerTensor.__index__ now fails for non-integral dtypes
This mirrors NumPy behavior, e.g. prior to this change

>>> tf.constant(42.0).__index__()
42
>>> np.array(42.0).__index__()
Traceback (most recent call last):
  File "...", line 1, in <module>
    np.array(42.0).__index__()
TypeError: only integer scalar arrays can be converted to a scalar index

If this breaks you, explicitly cast the tensor to an integral type
before using it as an index.

PiperOrigin-RevId: 274338898