Fixing what I think a bug introduced by cl/228373932, which resulted in some of our eval_test/eval_train jobs to fail with: AttributeError: 'NoneType' object has no attribute 'save_summary_steps'. Here's an example: http://screen/UentDg6uAZ6
I'm not familiar with the code and it's not clear to me how 'config' gets its value. So, feel free to suggest a different fix or rollback cl/228373932.

PiperOrigin-RevId: 229293332