Remove invalid/misleading test.
The test removed in this commit was invalid and only accidentally
passed because self.cached_session() forces placement of all operations
on CPU (since use_gpu defaults to False).

The implementation of Variables.initialized_value() creates a tf.cond
which is not forcefully colocated with the variable, hence running this
test with "self.cached_session(use_gpu=True)" would fail with:

AssertionError: '/device:CPU:0' != ''

This test was made invalid by
https://github.com/tensorflow/tensorflow/commit/b25d1c7d3e9f30925aa132ba62e79d281191a3dc
(see changes to tensorflow/python/ops/variables.py)

I don't think the test was actually useful, so removing it altogether.

PiperOrigin-RevId: 222084451